[profile.default]
src = 'contracts'
out = 'forge-artifacts'
libs = ['node_modules', 'lib']
test = 'test/foundry'
# cache_path = 'forge-cache'
allow_paths = ['./', '../', '../../node_modules']
remappings = [
    # 'ds-test/=../../pvt/lib/forge-std/lib/ds-test/src/',
    # 'forge-std/=../../pvt/lib/forge-std/src/',
    '@openzeppelin/=../../node_modules/@openzeppelin/',
    '@hop-protocol/=../',
]
optimizer = true
optimizer_runs = 500000
solc_version = '0.8.9'
# ignored_error_codes = [8261]

# [fuzz]
# runs = 10000
# max_test_rejects = 60000

# [profile.intense.fuzz]
# verbosity = 3
# runs = 100000
# max_test_rejects = 600000
